### ISSUE TITLE
Not compatible with new version ULauncher

### ISSUE THREAD

**Issue by Hahlh** [brpaz/ulauncher-mailinator#4]
![image](https://user-images.githubusercontent.com/45669613/64928028-1fc17700-d81b-11e9-8a1d-50a40e4b2fff.png)
Thank you a lot for creating so many awesome extensions for the launcher, Bruno!

**Comment by brpaz** [comment]
Sorry for the delay, but as you said I have created many extensions. It´s hard to keep everything updated. ;)

Should be fixed now.
